- name: Configure Local Machine
  hosts: localhost
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
    
    - name: Install apt packages
      apt:
        name:
          - git
          - curl
          - wget
          - tar
          - unzip
          - software-properties-common
        state: present

    - name: ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: 0xProto exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/0xProto"
      register: font_exists
      ignore_errors: yes

    - name: Download 0xProto
      when: font_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/0xProto.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes

    - name: Install zsh and oh-my-zsh
      script: scripts/zsh.sh

    - name: Install Anaconda
      script: scripts/anaconda.sh

    - name: Install Poetry
      script: scripts/poetry.sh
    
    - name: Install Python 3.11
      script: scripts/python3_11.sh
    
    - name: Install Zoxide
      script: scripts/zoxide.sh
    
    - name: Install Neovim
      script: scripts/neovim.sh

    - name: Install Astrovim
      script: scripts/astrovim.sh
    
    - name: Install Docker
      script: scripts/docker.sh
